[project]
site_name = "ggsci for Python"
site_description = "Plotnine color palettes inspired by plots in scientific journals, data visualization libraries, science fiction movies, and TV shows"
site_author = "Nan Xiao"
site_url = "https://nanx.me/py-ggsci/"
repo_url = "https://github.com/nanxstats/py-ggsci"
repo_name = "nanxstats/py-ggsci"
edit_uri = "edit/main/docs/"
copyright = """
Copyright &copy; 2026 py-ggsci authors
"""

nav = [
    { "Home" = "index.md" },
    { "Articles" = [
        { "Get started" = "articles/get-started.md" },
    ] },
    { "API reference" = [
        { "Discrete scales" = [
            { "NPG" = "reference/npg.md" },
            { "AAAS" = "reference/aaas.md" },
            { "NEJM" = "reference/nejm.md" },
            { "Lancet" = "reference/lancet.md" },
            { "JAMA" = "reference/jama.md" },
            { "BMJ" = "reference/bmj.md" },
            { "JCO" = "reference/jco.md" },
            { "UCSCGB" = "reference/ucscgb.md" },
            { "D3" = "reference/d3.md" },
            { "Gephi" = "reference/gephi.md" },
            { "Observable" = "reference/observable.md" },
            { "Primer" = "reference/primer.md" },
            { "Atlassian" = "reference/atlassian.md" },
            { "iTerm" = "reference/iterm.md" },
            { "LocusZoom" = "reference/locuszoom.md" },
            { "IGV" = "reference/igv.md" },
            { "COSMIC" = "reference/cosmic.md" },
            { "UChicago" = "reference/uchicago.md" },
            { "Star Trek" = "reference/startrek.md" },
            { "Tron Legacy" = "reference/tron.md" },
            { "Futurama" = "reference/futurama.md" },
            { "Rick and Morty" = "reference/rickandmorty.md" },
            { "The Simpsons" = "reference/simpsons.md" },
            { "Flat UI" = "reference/flatui.md" },
            { "Frontiers" = "reference/frontiers.md" },
        ] },
        { "Continuous scales" = [
            { "GSEA" = "reference/gsea.md" },
            { "Bootstrap 5" = "reference/bs5.md" },
            { "Material Design" = "reference/material.md" },
            { "Tailwind CSS" = "reference/tw3.md" },
        ] },
    ] },
    { "Changelog" = "changelog.md" },
]

extra_css = ["stylesheets/extra.css"]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
logo = "assets/logo.png"
favicon = "assets/favicon.png"
language = "en"
font = false

features = [
    "announce.dismiss",
    "content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    #"navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    #"navigation.instant.progress",
    "navigation.path",
    #"navigation.prune",
    "navigation.sections",
    #"navigation.tabs",
    #"navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    #"toc.follow",
    #"toc.integrate",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
repo = "fontawesome/brands/github"

# ----------------------------------------------------------------------------
# Section for configuring mkdocstrings plugin
# ----------------------------------------------------------------------------
[project.plugins.mkdocstrings]
default_handler = "python"

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
inherited_members = true
show_root_heading = true
show_source = false

# ----------------------------------------------------------------------------
# Section for configuring markdown-exec plugin
# ----------------------------------------------------------------------------
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
    { name = "python", class = "python", validator = "markdown_exec.validator", format = "markdown_exec.formatter" },
]
